# Generated by Django 2.2 on 2020-10-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=15)),
                ('suit', models.CharField(max_length=15)),
                ('color', models.CharField(default='Black', max_length=10)),
                ('face', models.BooleanField(default='false')),
            ],
        ),
    ]
